language: mn

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 200

policies:
- name: RulePolicy
  core_fallback_threshold: 0.30
  core_fallback_action_name: "utter_fallback"
  enable_fallback_prediction: true
assistant_id: 20250226-143611-azure-plant
