language: mn
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 200
policies:
  - name: RulePolicy
  - name: MemoizationPolicy
  - name: TEDPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.55  # Reduce from 0.65 to allow slightly lower confidence
    core_threshold: 0.30
    fallback_action_name: "utter_fallback"

assistant_id: 20250226-084145-best-dataset
