language: mn
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 200
policies:
- name: FallbackPolicy
  nlu_threshold: 0.4
- name: RulePolicy
- name: MemoizationPolicy
assistant_id: 20250226-084145-best-dataset
